{"date": "20240907-084854", "backend": "vllm", "model_id": "neuralmagic/Meta-Llama-3.1-70B-Instruct-FP8", "tokenizer_id": "neuralmagic/Meta-Llama-3.1-70B-Instruct-FP8", "best_of": 1, "use_beam_search": false, "num_prompts": 80, "request_rate": "inf", "duration": 10.12069097100175, "completed": 28, "total_input_tokens": 8311, "total_output_tokens": 1883, "request_throughput": 2.766609521052153, "input_throughput": 821.1889903380159, "output_throughput": 186.0544902907573, "mean_ttft_ms": 1152.3317481442064, "median_ttft_ms": 1152.871648002474, "std_ttft_ms": 780.2995259222297, "p99_ttft_ms": 2907.5256474741036, "mean_tpot_ms": 60.40919380032017, "median_tpot_ms": 47.97625879115542, "std_tpot_ms": 22.976709276238875, "p99_tpot_ms": 107.5509643125406, "mean_itl_ms": 438.0110939951749, "median_itl_ms": 333.37789299548604, "std_itl_ms": 210.98710499234485, "p99_itl_ms": 1033.4413656778634, "mean_latency_ms": 1701.4776083997276, "median_latency_ms": 0.0, "std_latency_ms": 2952.3240633573623, "p99_latency_ms": 9927.094235887924, "input_lens": [13, 25, 27, 10, 329, 29, 399, 328, 4, 205, 16, 372, 403, 9, 12, 770, 227, 8, 14, 390, 659, 59, 76, 744, 619, 279, 344, 9, 10, 45, 11, 4, 80, 768, 317, 40, 619, 8, 298, 16, 17, 696, 575, 11, 7, 281, 12, 147, 481, 770, 336, 6, 331, 9, 45, 222, 802, 481, 93, 641, 22, 15, 16, 77, 32, 689, 178, 9, 628, 480, 42, 336, 24, 515, 761, 112, 113, 348, 82, 467], "output_lens": [120, 0, 92, 194, 101, 0, 0, 0, 6, 69, 0, 0, 0, 45, 0, 9, 173, 0, 0, 37, 0, 0, 52, 76, 0, 45, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 17, 204, 11, 207, 78, 0, 26, 0, 100, 6, 0, 0, 0, 9, 0, 206, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "ttfts": [1.1841403319995152, 1.1837642630125629, 1.1837394370086258, 1.1836529889988014, 1.1835956550057745, 1.1834573630039813, 0.0, 0.0, 1.183129558005021, 1.346324251004262, 1.3462703280092683, 0.0, 1.3524521450017346, 1.3523552989936434, 1.9616940059931949, 1.9614268460136373, 1.9613639929884812, 1.961340932000894, 1.961265606994857, 1.9623657970078057, 10.069261048003682, 2.406568423990393, 2.9075774170050863, 2.9073856780014466, 0.0, 2.406145793996984, 4.568449671001872, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.8296073349920334, 0.8294408410001779, 0.8292636060068617, 0.8294237770023756, 0.8293238600017503, 0.828997698990861, 0.8289599700074177, 0.0, 1.130713940001442, 1.130460875996505, 1.1303525919938693, 0.0, 1.12988528200367, 1.129862340996624, 1.129999199998565, 1.175029356003506, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], "itls": [[0.6873954629991204, 0.5361799910024274, 0.5009070889936993, 0.33338490000460297, 0.3281412289943546, 0.47758900800545234, 0.5225197749969084, 0.3348161979956785, 0.32355709200783167, 0.481526331990608, 0.4145783460116945, 0.3214802039874485], [0.6873732859967276, 0.5361985909985378, 0.5008994150120998, 0.3321830079948995, 0.3288088679983048, 0.4781289789971197, 0.522522661005496, 0.33482721699692775, 0.3234931049955776, 0.4815634380065603, 0.4138921739940997, 0.33001725299982354, 0.3230147670110455, 0.3228604629985057, 0.3265009049937362, 0.32304067100631073, 0.3232048039935762, 0.32365772100456525, 0.3278751920006471, 0.32579317699128296, 0.5141656449995935, 0.506930072006071], [0.6873753130057594, 0.5361901139986003, 0.5009004290041048, 0.33337079800548963, 0.3281402129941853, 0.4783106249960838, 0.5218277700041654, 0.33480592600244563, 0.32420723600080237, 0.3205052379926201], [0.687382450007135, 0.5367050130007556, 0.5003820179990726, 0.33337789299548604, 0.3281445519969566, 0.47831125700031407, 0.5218100700003561, 0.33480654400773346, 0.3242031559930183, 0.4808232270006556, 0.4145582710043527, 0.32926590800343547, 0.3234179779974511, 0.3224810879910365, 0.32648291400983, 0.3230435339937685, 0.32319960300810635, 0.32365960598690435, 0.327875524002593, 0.31955806200858206], [0.6873711990047013, 0.5367059209966101, 0.5009816960082389, 0.3327774069912266, 0.32814104000863153, 0.4783137749909656, 0.5223669730039546, 0.3345461599965347, 0.323908267004299, 0.47963634399638977], [0.6873808200034546, 0.536704281999846, 0.5009873759991024, 0.33276324899634346, 0.32813811300729867, 0.478317237997544, 0.5223838679958135, 0.33453963200736325, 0.323896377987694, 0.4807657550118165, 0.4145669469871791, 0.3292542700073682, 0.3234324189979816, 0.3224511000007624, 0.3264904160023434, 0.32304641300288495, 0.32359303599514533, 0.32326831300451886, 0.32787259499309584, 0.32572578999679536, 0.5141610610007774, 0.5069223820028128], [], [], [0.49709451000671834], [0.5240773810073733, 0.5366853540035663, 0.5009905949991662, 0.3327592159912456, 0.3281384750007419, 0.47831939700699877, 0.32837618899066], [0.524065260993666, 0.5366865540127037, 0.5009847119945334, 0.332762913996703, 0.32814446500560734, 0.47831469599623233, 0.5223151420068461, 0.3345441549899988, 0.32389317599881906, 0.48076008001226, 0.41456726999604143, 0.3292544239957351, 0.3234265530045377, 0.32245246499951463, 0.3264993539924035, 0.323047823010711, 0.3235726929997327, 0.3232916010019835, 0.3278705799893942, 0.3257234970078571, 0.5141606469987892, 0.5069065499992575], [], [0.517515398998512, 0.5366842000075849, 0.5009840550046647, 0.3327676969929598, 0.3281620890047634, 0.47829335799906403, 0.5223201479966519, 0.3345309870055644, 0.3239011989935534, 0.4807585910020862, 0.41456991199811455, 0.32953402800194453, 0.32312670699320734, 0.32245562299794983, 0.3265505740127992, 0.3233838559972355, 0.32319861599535216, 0.32329472800483927, 0.3282360329903895, 0.32535403200017754, 0.5141616309992969, 0.5068787560012424], [0.5175200469966512, 0.5366936049977085, 0.500982842000667, 0.3332019359950209, 0.3190390460076742], [0.4448843790014507, 0.500973314003204, 0.33320377400377765, 0.327656321998802, 0.47829875399474986, 0.5223106449993793, 0.3345392760093091, 0.3239071079879068, 0.48074907800764777, 0.41456732399819884, 0.32954673799395096, 0.32310906299971975, 0.3227940190117806, 0.32621558698883746, 0.3233839830063516, 0.32320330299262423, 0.32364330600830726, 0.3278034169925377, 0.32537634500477, 0.514156624005409, 0.5072452489985153], [0.3293942390009761], [0.44487401899823453, 0.5009765319991857, 0.333187241005362, 0.32768208099878393, 0.47828467399813235, 0.5223139629961224, 0.33453916599683, 0.3239018590102205, 0.4807537859887816, 0.4145675620093243, 0.32955612600198947, 0.3231059149984503, 0.3224567989964271, 0.32653982400370296, 0.3233869619871257, 0.32320352000533603, 0.3236699260014575, 0.31756179900548887], [0.44488935499975923, 0.5009841049904935, 0.3331958030030364, 0.3276427340024384, 0.4783183179970365, 0.522311010005069, 0.33454341799370013, 0.32389246599632315, 0.48079059600422624, 0.4145370409969473, 0.3295559329999378, 0.32310421600413974, 0.3227920680074021, 0.32656186999520287, 0.3230282860022271, 0.3232039860013174, 0.32366002099297475, 0.32779670000309125, 0.32537883300392423, 0.5141514639981324, 0.5072394969902234], [0.44489609899756033, 0.500995046008029, 0.333194997991086, 0.32764273800421506, 0.47832228199695237, 0.5223073020024458, 0.33455498100374825, 0.3238682270020945, 0.48079976098961197, 0.41454147901094984, 0.3295508029987104, 0.3231029669987038, 0.3227991129970178, 0.32656424699234776, 0.3230299490096513, 0.3231969240005128, 0.32365835800010245, 0.3277946189919021, 0.3253918789996533, 0.514145343011478, 0.5072268869989784], [0.4444416090118466, 0.5002703749923967, 0.33318150299601257, 0.3276394330023322, 0.3163153030036483], [], [0.5002755079913186, 0.3331920659984462, 0.3276415850123158, 0.4782578599988483, 0.5223089700011769, 0.33454358999733813, 0.32416104699950665, 0.48051373699854594, 0.4145461610023631, 0.3295502859982662, 0.3231020099919988, 0.3227969550061971, 0.3265628840017598, 0.3230317580018891, 0.32319886499317363, 0.32366686800378375, 0.3277917789964704, 0.32537373100058176, 0.5141589980048593, 0.5072126449958887], [1.1389414760051295, 0.5224021979956888, 0.3341187810001429, 0.3239212540065637, 0.5654734739946434, 0.32990141899790615, 0.3292383340012748, 0.31593018100829795], [0.33256509600323625, 0.8063648009992903, 0.522442247995059, 0.3338630810030736, 0.32416081900009885, 0.5623921910009813, 0.3329939669929445, 0.3292228240024997, 0.323107065007207, 0.3227978089998942, 2.465651374994195, 0.3261836180026876], [], [0.5002827100106515, 0.33318143799260724, 0.32763872999930754, 0.478258012997685, 0.32777751100366004], [1.2234853240079246, 0.32990194000012707, 3.4407245879992843, 0.5052763400017284], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [1.0333939850097522, 0.4231600899947807], [1.0333924520091387, 0.5370401249965653, 0.5009805799927562, 0.33035549800843, 0.3305907829926582, 0.47817582500283606, 0.5225722900067922, 0.3347968609887175, 0.32107452100899536, 0.48356621200218797, 0.41264882699761074, 0.33191783700021915, 0.3229711199965095, 0.32092327999998815, 0.32832284600590356, 0.32305474499298725, 0.323196248995373, 0.32363843799976166, 0.3278954380075447, 0.3255554929928621, 0.32167244200536516], [1.0333942249999382], [1.0334386059985263, 0.5369413689913927, 0.5009197420004057, 0.3305307080008788, 0.33040696900570765, 0.47818266600370407, 0.5226036910025869, 0.33476117899408564, 0.32123171200510114, 0.48338705199421383, 0.41302338399691507, 0.3315431930095656, 0.32298680298845284, 0.3210940960125299, 0.32815623699571006, 0.3230541349912528, 0.3231948450120399, 0.32364877600048203, 0.3278885279869428, 0.3255893349996768, 0.32167138101067394], [1.0334368030016776, 0.5369380129995989, 0.5008978260011645, 0.330548790996545, 0.3304281269956846, 0.4781450330046937, 0.5226014939980814, 0.32745172100840136], [1.0334439769940218, 0.5369689080107491, 0.5009851299982984, 0.33049297699471936, 0.33044873700418975, 0.4781787819956662, 0.5225951930042356, 0.33477169800607953, 0.32108241599053144, 0.4835420090093976, 0.41299765699659474, 0.3315855789987836, 0.3229858900012914, 0.32105295099609066, 0.32817756199801806, 0.3230539350042818, 0.32319600399932824, 0.3236371800012421, 0.3278982899937546, 0.32556944800307974, 0.5145393580023665, 0.5069234859984135], [1.0334414219978498, 0.5369317370059434, 0.32730488300148863], [], [0.7317331910016946, 0.5369280750019243, 0.500915984986932, 0.33216483501018956, 0.3287986740033375, 0.47813438398588914, 0.522535254000104, 0.3348100000002887, 0.3233507380064111, 0.48089263499423396], [0.5428310189890908], [0.731725721998373, 0.5369333470007405, 0.5009044000034919, 0.332175550996908, 0.32879993799724616, 0.4781357890024083, 0.5225452829909045, 0.33479852600430604, 0.3232819310069317, 0.48133091899217106, 0.414385605006828, 0.3301099410018651, 0.32298464298946783, 0.3228136940015247, 0.3265036700031487, 0.3230438989994582, 0.32320830300159287, 0.3236522410006728, 0.327879798001959, 0.32551531300123315, 0.51452844600135, 0.5069396879989654], [], [0.7318869239970809, 0.5369412690051831, 0.5009050319931703, 0.3321844849997433, 0.32877543300855905, 0.4781598419940565, 0.5225580240075942, 0.33476540799892973, 0.32326194299093913, 0.481362557009561, 0.41300087999843527, 0.3315214379981626, 0.32298751099733636, 0.32111649800208397, 0.3281725400011055, 0.32304578699404374, 0.32320471400453243, 0.32365248299902305, 0.32786884100642055, 0.3255498069920577, 0.5145286250044592, 0.5069199970021145], [0.5430299519939581], [0.7317601769900648, 0.5369009690039093, 0.500904372005607, 0.332174868992297, 0.328801914001815, 0.47813280500122346, 0.5225399490009295, 0.33481303599546663, 0.3233858029998373, 0.48116425701300614, 0.4143848299863748, 0.3300681200053077, 0.3229913929972099, 0.32285123800102156, 0.32650291599566117, 0.32304413300880697, 0.32320539400097914, 0.3236531750007998, 0.3278828159964178, 0.32547115700435825, 0.5145385789946886, 0.5069546120066661], [0.6873685769969597, 0.5362125109968474, 0.5009012630034704, 0.3321844589954708, 0.3288157280039741, 0.47812066599726677, 0.5225398730108282, 0.3348158919980051, 0.32342347399389837, 0.48111317900475115, 0.41439200899912976, 0.33003259399265517, 0.3230179509992013, 0.32286362700688187, 0.3264899640053045, 0.3230437819875078, 0.3232039430004079, 0.3236550200090278, 0.3278808670002036, 0.3257785369933117, 0.32116304300143383], [], [], [], [], [], [], [], [], [], [], [], [], [], []], "generated_texts": ["? It\u2019s a great book about how to run a business using the Entrepreneurial Operating System (EOS). One of the key concepts in the book is the idea of a \u201cVisionary\u201d and an \u201cIntegrator.\u201d The Visionary is the person who has the big ideas and sees the future of the company, while the Integrator is the person who takes those ideas and makes them a reality.\nIn many companies, the Visionary and Integrator are the same person, but as the company grows, it can be helpful to have two separate people in these roles. The Visionary can focus on", "", " and understand. Also, you need to add some new information to the \"How to use\" part. Please see the attached file for more details.\nI can help you with reformatting the Filters part and adding new information to the \"How to use\" part. Please provide the attached file so I can review the details and get started on the \"second draft\". I'll make sure to make it easy to read and understand. Let's get started!", " a pull? and a passive?\nIn the Jobs To Be Done (JTBD) context, a \"push,\" \"pull,\" and \"passive\" refer to the different ways in which a customer's needs or circumstances can drive them to adopt a new solution or product. Here's a brief explanation of each:\n\n**Push**: A push refers to a situation where a customer is forced to adopt a new solution due to a change in their circumstances or environment. This can be due to external factors such as a change in government regulations, a shift in market trends, or a disruption in their current workflow. In a push scenario, the customer is essentially \"pushed\" into adopting a new solution because their current situation is no longer tenable.\n\nExample: A company is forced to adopt a new accounting software due to a change in tax laws that requires them to track expenses in a specific way.\n\n**Pull**: A pull refers to a situation where a customer is attracted to", "\n\n\n\n**Project Charter Template**\n\n**Project Title:** [Insert Project Title]\n\n**Project Sponsor:** [Insert Project Sponsor's Name]\n\n**Project Manager:** [Insert Project Manager's Name]\n\n**Date:** [Insert Date]\n\n**Project Overview:**\n\nThe purpose of this project is to [insert brief project description]. The project aims to [insert project objectives].\n\n**Project Scope:**\n\nThe scope of this project includes:\n\n* [Insert scope statement]\n\n**Project Objectives:**\n\nThe objectives of this project are", "", "", "", " is a simple, open-source", " is a noun that refers to a procedure for critical evaluation, a means of determining the presence, quality, or truth of something, or a trial. What are some synonyms for the noun \"test\"? \n\nAnswer: Some synonyms for the noun \"test\" include essay, experiment, experimentation, trial, exam, examination, quiz, and sample.", "", "", "", " According to various sources, including Bible Gateway and YouVersion, the most quoted biblical verse is John 3:16, which states: \u201cFor God so loved the world that he gave his one and only begotten Son,", "", "swift\nextension AppDelegate: GIDSignInDelegate", " \n\nThe book is correct in that the syntax is correct for c++20 and later. The issue is that your compiler is not set to use C++20 or later by default. \n\nThe error message you're seeing is telling you that the `using enum` syntax is not available in the version of C++ that your compiler is currently using. \n\nTo fix this, you need to tell your compiler to use C++20 or later. The exact way to do this will depend on your compiler and development environment. Here are a few common ways to do this:\n\n*   If you're using Visual Studio, you can set the C++ language standard in the project properties. To do this, follow these steps:\n    *   Open the project properties by right-clicking on the project in the Solution Explorer and selecting \"Properties\".\n    *   In the properties", "", "", " \n\nPlease note that you need to create a `Login` component in the `components` directory for this code to work. The `Login` component should contain the JSX for the login", "", "", " I will also keep in mind the specific requirements of the task, such as the word count, tone, and style. I will do my best to produce high-quality content that meets your needs. Please provide the specific task details, and I will get started!", " should take when repudiating a building contract.\n* Explain the importance of following the correct procedures and seeking professional advice.\n\nH2: Conclusion\n\n* Summarize the key points discussed in the article.\n* Emphasize the importance of understanding the risks and consequences of repudiation in a building contract and the need for developers to carefully consider their options before making a decision.", "", "`\nI've made the following changes:\n\n*   Renamed `allColors` to `allColorsOriginal` to make it clear that this is the original list of colors.\n*   Created a new list `allColors`", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "php\nHere is the implementation of the classes:\n```php\nclass Database {\n   ", "\nNumPy broadcasting is a powerful feature that allows you to perform operations on arrays with different shapes and sizes. It's a way to align arrays with different numbers of dimensions for arithmetic operations. Here's an example to illustrate how broadcasting works:\nSuppose we have two arrays:\na = np.array([1, 2, 3])  # shape: (3,)\nb = np.array([4, 5, 6])  # shape: (3,)\nWe can add these arrays element-wise using the `+` operator:\nresult = a + b\nprint(result)  # [5, 7, 9]\nNow, let's introduce broadcasting. Suppose we have a 2D array `c` with shape `(2, 3)`:\nc = np.array([[1, 2, 3], [4, 5, 6]])  # shape: (2, 3)\nWe can add `a` to `c` using broadcasting:\nresult = c", " chili pepper plants, spaced about 30-45cm", " (Key Performance Indicators)\nGame developers KPIs (Key Performance Indicators) are metrics used to measure the performance and success of a game. These KPIs help game developers understand how their game is doing, identify areas for improvement, and make data-driven decisions to optimize the game's performance. Here are some common game developers KPIs:\n**Player Acquisition KPIs**\n\n1. **Daily Active Users (DAU)**: The number of unique users who play the game every day.\n2. **Monthly Active Users (MAU)**: The number of unique users who play the game every month.\n3. **New User Acquisition**: The number of new users who download and play the game.\n4. **Cost Per Acquisition (CPA)**: The cost of acquiring a new user, including marketing and advertising expenses.\n\n**Player Engagement KPIs**\n\n1. **Session Length**: The average time a player spends playing the game in a single session.\n2. **Session Frequency**: The number of times a player", " I'm a founder of a startup that is trying to create a new market category. I'm struggling to articulate the value proposition of my product. How can I effectively communicate the value proposition of my product to potential customers, investors, and partners?\nAs a founder creating a new market category, you're facing a classic challenge. I'll draw from the wisdom of legendary founders and investors to help", "", " \n\nI am looking forward to your answers. \n\nThank you for your time and effort. \n\nBest regards,\n[Your Name]", "", " \n\n![image](data:image/svg+xml,%3Csvg%20width%3D%2220%22%20height%3D%2220%22%3E%3Ccircle%20cx%3D%2210%22%20cy%3D%2210%22%20r%3D%2210%22%20fill%3D%22%23ff0000%22/%3E%3C/svg%3E)", "\n\n\n\n1. Create a file", "", "", "", " I'll do my best to assist you.", "", ".\n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], "errors": ["", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "", "", "", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "", "", "", "", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "", "", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "", "", "", "", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "", "", "", "", "", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "", "", "", "", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n", "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py\", line 94, in connection_lost\n    uncompleted = self._parser.feed_eof()\n  File \"aiohttp/_http_parser.pyx\", line 513, in aiohttp._http_parser.HttpParser.feed_eof\naiohttp.http_exceptions.TransferEncodingError: 400, message:\n  Not enough data for satisfy transfer length header.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/vllm-workspace/backend_request_func.py\", line 261, in async_request_openai_completions\n    async for chunk_bytes in response.content:\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 50, in __anext__\n    rv = await self.read_func()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 317, in readline\n    return await self.readuntil()\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 351, in readuntil\n    await self._wait(\"readuntil\")\n  File \"/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py\", line 312, in _wait\n    await waiter\naiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>\n"]}